### ISSUE TITLE
HTML Report Has Duplicates the previous Servers available builds

### ISSUE THREAD

**Issue by leejkl** [MateuszNad/SQLServerUpdatesModule#1]
See Attached Image
![2018-01-16_12-47-57](https://user-images.githubusercontent.com/21105217/35003873-2e975a8a-fabc-11e7-9d2c-18fe905b5684.png)

**Comment by MateuszNad** [comment]
Thanks for the issue and use my module. I repaired this mistake and now updates don't duplicate.
