### ISSUE TITLE
WARNING: The property 'Count' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by sueb-lex** [MateuszNad/SQLServerUpdatesModule#5]
Getting the above error when trying to run this.  Was previously working in June.

**Comment by KlausObd** [comment]
Same here :-(

**Comment by sueb-lex** [comment]
Hopefully someone will be able to fix this as it is an awesome script that I use monthly to check to see what SQL Servers need updates.  I have shared with others.  Very nice report that I can share with my Networking Group.

**Comment by MateuszNad** [comment]
It's nice to hear that somebody still is using this module. 
The module retrieves data from https://sqlserverupdates.com website. The tables were badly formatted on the website and therefore the script could not parse and create objects correctly.

It should be better now. Can you check it out and let me know?

**Comment by sueb-lex** [comment]
Tried the script again and it is working perfectly again.  I use this monthly and give the report to Networking to allow them to see what servers I will need to update.  Report is awesome and glad it is working again.  Thanks so much!

**Comment by KlausObd** [comment]
Hi,

 

thanks a lot. It works again like a charm <g>  As Sue also said, works now again …

 

Für Rücksprachen stehe ich gern zur Verfügung

 

mit freundlichen Grüßen aus Nürnberg 

 Klaus Oberdalhoff    |  Senior Consultant  |   Database Specialist 

Untere Schmiedgasse 8  |    D-90403 Nürnberg     |    Germany

Tel  : +49(911)2369666      |     Handy: +49(1515) 2 58 02 47

Email:  ***@***.***> ***@***.***      |    Fax  : 03212 / 1154718

Profil: auf Anfrage

 

Von: mnadobnik ***@***.*** 
Gesendet: Donnerstag, 25. August 2022 14:29
An: MateuszNad/SQLServerUpdatesModule ***@***.***>
Cc: Klaus Oberdalhoff ***@***.***>; Comment ***@***.***>
Betreff: Re: [MateuszNad/SQLServerUpdatesModule] WARNING: The property 'Count' cannot be found on this object. Verify that the property exists. (Issue #5)

 

It's nice to hear that somebody still is using this module.
The module retrieves data from https://sqlserverupdates.com website. The tables were badly formatted on the website and therefore the script could not parse and create objects correctly.

It should be better now. Can you check it out and let me know?

**Comment by MateuszNad** [comment]
Great to hear it :) Thanks for your confirmation.
